name: Rebase Pull Requests

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
    
jobs:
  check-and-rebase:
    runs-on: ubuntu-latest
    steps:          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need full commit history for rebase
          
      - name: Set Git user details
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          
      - name: Get branch to rebase
        id: get-rebase-branch
        uses: actions/github-script@v7
        with:
          script: |
            let pr = null;
            let page = 1;
            let perPage = 100;
            let fail_prs = [];
            let fail_emails = ''; // Should be comma separated with no space
            while (!pr) { // Loop until find PR to rebase, or no more PRs to check
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sort: 'created',
                direction: 'asc',
                per_page: perPage,
                page: page
              });
              const filteredPRs = prs.data.filter(potentialPR =>
                potentialPR.auto_merge !== null &&
                potentialPR.labels.some(label => label.name === 'auto-rebase')
              );

              for (const potentialPR of filteredPRs) {
                try { // Try rebase, if conflict then try next branch
                  console.log(`Checking ${potentialPR.url}`);
                  console.log(potentialPR.user);
                  await exec.exec(`git fetch origin ${potentialPR.head.ref}`);
                  await exec.exec(`git fetch origin ${potentialPR.base.ref}`);
                  await exec.exec(`git checkout ${potentialPR.head.ref}`);
                  await exec.exec(`git rebase ${potentialPR.base.ref}`);
                  await exec.exec(`git checkout main`);
                  pr = potentialPR;
                  break;
                } catch (error) {
                  console.log(`PR #${potentialPR.number} cannot be rebased: ${error.message}`);
                  await exec.exec(`git rebase --abort`);
                  await exec.exec(`git checkout main`);
                  fail_prs.push(potentialPR.number);
                }
              }
              
              if (prs.data.length < perPage) {
                break;
              }
              page += 1;
            }
            if (pr) {
              core.notice('PR to rebase: ' + pr.html_url);
              core.setOutput('BRANCH', pr.head.ref);
              core.setOutput('SUCCESS_PR', pr.number);
              core.setOutput('FAIL_PRS', fail_prs);
            } else {
              console.log('No PR to rebase');
              core.notice('No PR to rebase.')
              core.setOutput('BRANCH', '');
              core.setOutput('SUCCESS_PR', '');
              core.setOutput('FAIL_PRS', fail_prs);
            }
      
      - name: Rebase
        if: ${{ steps.get-rebase-branch.outputs.BRANCH != '' }}
        run: |
          branch=${{ steps.get-rebase-branch.outputs.BRANCH }}
          git checkout $branch
          git push origin $branch --force-with-lease

      - name: Post Comment
        uses: actions/github-script@v7
        with:
          script: |
            const failPrs = JSON.parse('${{ steps.get-rebase-branch.outputs.FAIL_PRS }}'); // Array of fail PR numbers
            const successPr = '${{ steps.get-rebase-branch.outputs.SUCCESS_PR }}'; // Success PR number
            const failBody = `❌ **Auto Rebase Failed**`
            const successBody = `✅ **Auto Rebase Successed**`
            async function deletePreviousComment(prNumber) {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });
              const previousComment = comments.data.find(comment => comment.body.includes("Auto Rebase") && comment.user.type === 'Bot');
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: previousComment.id
              });
            }
            
            console.log('Posting comment on failed PRs...');
            for (const pr of failPrs) {
              await deletePreviousComment(pr);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr,
                body: failBody
              });
            }

            console.log('Posting comment on successed PR...');
            await deletePreviousComment(successPr);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: successPr,
              body: successBody
            });            
      # - name: Send emails
      #   uses: dawidd6/action-send-mail@v6
      #   with:
