name: Rebase Pull Requests

on:
  push:
    branches:
      - main
permissions:
  contents: write
    
jobs:
  check-and-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need full commit history for rebase

      - name: Get branch to rebase
        id: get-rebase-branch
        uses: actions/github-script@v7
        with:
          script: |
            let pr = null;
            let page = 1;
            let perPage = 100;

            while (!pr) { // Loop until find PR to rebase, or no more PRs to check
              const prs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sort: 'created',
                direction: 'asc',
                per_page: perPage,
                page: page
              });
              pr = prs.data.find(pr =>
                pr.auto_merge !== null &&
                pr.labels.some(label => label.name === 'auto-rebase')
              );
              if (prs.data.length < perPage) {
                break;
              }
              page += 1;
            }
            if (pr) {
              // console.log(pr);
              core.setOutput('BRANCH', pr.head.ref);
            } else {
              console.log("No PR to rebase");
              core.setOutput('BRANCH', '');
            }
            
      - name: Set Git user details
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Rebase
        run: |
          branch=${{ steps.get-rebase-branch.outputs.BRANCH }}
          git fetch origin $branch
          git checkout $branch
          git rebase origin/main
          git push origin $branch --force-with-lease
