name: Bump Version

on:
  release:
    types: [published]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Bump version"
        run: |
          release=$(echo ${{ github.ref }} | sed 's|^refs/tags/||')
          if [[ $release == release/* ]]; then
            new_version=$(echo 'release/3.1.2' | cut -d'/' -f2)
            echo $new_version
          else
            exit 1
          fi

          old_version=$(cat ${{ github.workspace }}/version)
          if dpkg --compare-versions $new_version gt $old_version; then
            echo yes
            echo $new_version > version
          else
            echo no
            exit 1
          fi

      - name: "Commit version change"
        if: ${{ success() }}
        run: |
          git add version
          git commit -m "Bump version to $new_version"

      - name: "Push changes"
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
