name: multi
on:
  push

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          quotepath: false

      - name: 'Set output in the matrix format'
        id: set-output
        run: echo "changed_directories={\"dir\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  do-stuff:
    runs-on: ubuntu-latest
    if: ${{ needs.find-out-changes.outputs.changed_directories != '' }}
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.changed_directories)}}
    needs:
      - find-out-changes
    steps:
      - uses: actions/checkout@v4
      - uses: jenseng/dynamic-uses@v1
        with:
          uses: ./${{ matrix.dir }}/.github