name: multi
on:
  push

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          quotepath: false
          separator: ','

      - name: 'Set output in the matrix format'
        id: set-output
        run: echo "workflows=${{ steps.changed-files.outputs.all_changed_files }}" >> "$GITHUB_OUTPUT"
        
  call-app-one:
    runs-on: ubuntu-latest
    needs: find-out-changes
    if: contains(${{ needs.find-out-changes.outputs.changed_directories }}, 'apps/one')
    steps:
      - uses: actions/checkout@v4
      - name: Call Reusable Workflow One
        uses: ./apps/one/.github

  call-app-two:
    runs-on: ubuntu-latest
    needs: find-out-changes
    if: contains(${{ needs.find-out-changes.outputs.changed_directories }}, 'apps/two')
    steps:
      - uses: actions/checkout@v4
      - name: Call Reusable Workflow Two
        uses: ./apps/two/.github

  call-app-three:
    runs-on: ubuntu-latest
    needs: find-out-changes
    if: contains(${{ needs.find-out-changes.outputs.changed_directories }}, 'apps/three')
    steps:
      - uses: actions/checkout@v4
      - name: Call Reusable Workflow Three
        uses: ./apps/three/.github