name: Notify PR Updates

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  process-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Rebase Labeled PRs
        run: |
          # Fetch all open PRs
          prs=$(gh pr list --state open --json number --jq '.[].number')
          echo "Found PR numbers: $prs"
          
          for pr in $prs; do
            # Fetch labels for each PR
            labels=$(gh pr view $pr --json labels --jq '.labels | map(.name)')
          
            # Check for the 'auto-rebase' label
            if echo $labels | grep -q "auto-rebase"; then
              echo "PR #$pr has 'auto-rebase' label. Rebasing..."
              git checkout -b pr/$pr origin/pr/$pr
              git rebase origin/main
              git push --force-with-lease origin pr/$pr
            else
              echo "PR #$pr does not have 'auto-rebase' label. Skipping rebase..."
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
