name: Validate code in the PR



on:
  pull_request:


jobs:
  validate-pr:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Test the application
        run: |
          dotnet --version
          sleep 30
