name: Validate code in the PR

on:
  [pull_request]

jobs:
  validate-pr:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          pwd
          tree -a -I '.git'
          git status
      - name: Test the application
        run: |
          dotnet --version
          sleep 1
#      - name: Fail
#        uses: actions/github-script@v7
#        with:
#          script: |
#            github.rest.checks.create({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              head_sha: context.sha,
#              name: "Merge queue has failed",
#              status: "completed",
#              conclusion: "failure"
#            })

          