name: Manual Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
          
permissions:
  contents: write

jobs:
  bump_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "false"
        with:
          args: ${{ inputs.bump-type }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "release/${{ steps.bump.outputs.current-version }}"
          generate_release_notes: true
          make_latest: true