name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type'
        required: true
        default: 'auto'
        type: choice
        options:
          - major
          - minor
          - patch
          - auto
          
permissions:
  contents: write

jobs:
  bump_and_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Versioning
        id: versioning
        uses: ./.github/actions/versioning
        with:
          version-type: ${{ inputs.bump-type }}
          github-token: ${{ secrets.BOT_API_KEY }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.versioning.outputs.next-version }}"
          generate_release_notes: true
          make_latest: true