name: versioning

on:
  pull_request:
    types:
      - closed

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        echo ${BRANCH_NAME}